[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "moe-router-study"
version = "0.1.0"
description = "Research project studying routing patterns in Mixture of Experts models"
authors = [
    {name = "d0rbu", email = "your-email@example.com"},
]
dependencies = [
    "torch>=2.0.0",
    "transformers>=4.35.0",
    "nnterp>=0.4.7",
    "numpy>=1.24.0",
    "pandas>=2.0.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.12.0",
    "plotly>=5.15.0",
    "scikit-learn>=1.3.0",
    "wandb>=0.15.0",
    "datasets>=2.14.0",
    "tqdm>=4.65.0",
    "jupyter>=1.0.0",
    "ipywidgets>=8.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "mypy>=1.5.0",
]

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "mypy>=1.5.0",
]

[tool.black]
line-length = 88
target-version = ['py39']

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

