# Configuration for ty type checker

[rules]
possibly-unbound-attribute = "ignore"
invalid-return-type = "ignore"
call-non-callable = "ignore"
non-subscriptable = "ignore"
unresolved-attribute = "ignore"
unresolved-import = "ignore"
