# Configuration for ty type checker

[rules]
possibly-unbound-attribute = "ignore"
unsupported-operator = "ignore"
invalid-argument-type = "ignore"
no-matching-overload = "ignore"
unknown-argument = "ignore"
unresolved-attribute = "ignore"
unresolved-import = "ignore"
too-many-positional-arguments = "ignore"
invalid-return-type = "ignore"
invalid-parameter-default = "ignore"
invalid-assignment = "ignore"
