# Configuration for ty type checker
# Ignore certain error types that are causing issues in the existing codebase
# while still catching more serious type errors

[rules]
possibly-unbound-attribute = "ignore"
invalid-return-type = "ignore"
invalid-argument-type = "ignore"
non-subscriptable = "ignore"
unresolved-attribute = "ignore"
unknown-argument = "ignore"
unresolved-import = "ignore"
