name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python 3.12
      run: uv python install 3.12
    
    - name: Install dependencies
      run: |
<<<<<<< HEAD
        uv sync --extra dev
=======
        uv sync --dev
>>>>>>> f21a0d2 (Address all feedback: switch to ty, Python 3.12 only, run CI on all branches)
    
    - name: Run ruff linting
      run: |
        uv run ruff check .
    
    - name: Run ruff formatting check
      run: |
        uv run ruff format --check .
    
    - name: Run ty type checking
      run: |
        uv run ty check core/ exp/ viz/

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python 3.12
      run: uv python install 3.12
    
    - name: Install dependencies
      run: |
<<<<<<< HEAD
        uv sync --extra dev --extra ml
=======
        uv sync --dev
>>>>>>> f21a0d2 (Address all feedback: switch to ty, Python 3.12 only, run CI on all branches)
    
    - name: Run tests
      run: |
        uv run pytest test/ -v --cov=core --cov=exp --cov=viz --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
<<<<<<< HEAD

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.11
    
    - name: Install dependencies
      run: |
        uv sync --extra dev
    
    - name: Run safety check
      run: |
        uv run pip install safety
        uv run safety check --json || true  # Don't fail CI on security issues initially
    
    - name: Run bandit security linter
      run: |
        uv run pip install bandit
        uv run bandit -r core/ exp/ viz/ -f json || true  # Don't fail CI initially
=======
>>>>>>> f21a0d2 (Address all feedback: switch to ty, Python 3.12 only, run CI on all branches)
