name: CI

on:
  pull_request:

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python 3.12
      run: uv python install 3.12
    
    - name: Set Python version
      run: uv python pin 3.12
    
    - name: Create virtual environment
      run: uv venv
    
    - name: Install zstandard from wheel
      run: |
        uv pip install --only-binary=zstandard zstandard==0.22.0
    
    - name: Install dependencies
      run: |
        uv sync --dev --no-build-isolation
      env:
        UV_PRERELEASE: allow
    
    - name: Run ruff linting
      run: |
        uv run ruff check .
    
    - name: Run ruff formatting check
      run: |
        uv run ruff format --check .
    
    - name: Run ty type checking
      run: |
        uv run ty check core/ exp/ viz/ test/

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python 3.12
      run: uv python install 3.12
    
    - name: Set Python version
      run: uv python pin 3.12
    
    - name: Create virtual environment
      run: uv venv
    
    - name: Install zstandard from wheel
      run: |
        uv pip install --only-binary=zstandard zstandard==0.22.0
    
    - name: Install dependencies
      run: |
        uv sync --dev --no-build-isolation
      env:
        UV_PRERELEASE: allow
    
    - name: Run tests
      run: |
        uv run pytest test/ -v --cov=core --cov=exp --cov=viz --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
